### ISSUE TITLE
And operator is bitwise

### ISSUE THREAD

**Issue by Nereh** [fdipuma/scrima-dotnet#6]
https://github.com/fdipuma/scrima-dotnet/blob/d1140e4e8b9e47f72d3a6bd9ee37ae51925bb7cf/src/Scrima.Queryable/ScrimaExtensions.Where.cs#L88

This is actually a bitwise And operator on the expression see [here](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression.and?view=net-6.0#system-linq-expressions-expression-and(system-linq-expressions-expression-system-linq-expressions-expression))

You should instead use AndAlso seen [here](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression.andalso?view=net-6.0#system-linq-expressions-expression-andalso(system-linq-expressions-expression-system-linq-expressions-expression))

I noticed this issue when debugging some queries with an "and" on an IQueryable in cosmos db. The query resolves to "condition1 & condition2" instead of "condition1 and condition2". Works perfectly fine for regular queryables but for whatever reason cosmos decides to make the distinction between the two different ands.

Would it be possible to change this or at least allow a config to change this behavior?

**Comment by fdipuma** [comment]
Hey @Nereh! Sorry for the late reply, seems totally reasonable, I'll try to take a look as soon as I can.

It seems to me that should be possible to change `And` to `AndAlso` without breaking anything.
